[package]
name = "rs_physics"
authors = ["Brandon White"]
description = "A simple physics library written in Rust"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[dependencies]
