name: Rust

on:
  push:
    branches: [ "nightly" ]
  pull_request:
    branches: [ "nightly" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nightly
      run: rustup toolchain install nightly
    - name: Nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
